// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8sL-0b52F8OQwXR6GxZEXwcFcyyLS0sM',
    appId: '1:140559833535:web:5e7b3f6080dfe525d5e90a',
    messagingSenderId: '140559833535',
    projectId: 'allfixsapp',
    authDomain: 'allfixsapp.firebaseapp.com',
    storageBucket: 'allfixsapp.appspot.com',
    measurementId: 'G-6P6TYGBDS0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXjsSTHBtA2vszAxFC2J7yKT3hX-6U6gw',
    appId: '1:140559833535:android:9aa5b351b5da40f0d5e90a',
    messagingSenderId: '140559833535',
    projectId: 'allfixsapp',
    storageBucket: 'allfixsapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJYG3svynXroUOrnL9qYzh5FkKwiUbpe0',
    appId: '1:140559833535:ios:e84c2dd1b3a10761d5e90a',
    messagingSenderId: '140559833535',
    projectId: 'allfixsapp',
    storageBucket: 'allfixsapp.appspot.com',
    iosBundleId: 'com.example.allFixs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJYG3svynXroUOrnL9qYzh5FkKwiUbpe0',
    appId: '1:140559833535:ios:e84c2dd1b3a10761d5e90a',
    messagingSenderId: '140559833535',
    projectId: 'allfixsapp',
    storageBucket: 'allfixsapp.appspot.com',
    iosBundleId: 'com.example.allFixs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8sL-0b52F8OQwXR6GxZEXwcFcyyLS0sM',
    appId: '1:140559833535:web:72af738f9c9dd488d5e90a',
    messagingSenderId: '140559833535',
    projectId: 'allfixsapp',
    authDomain: 'allfixsapp.firebaseapp.com',
    storageBucket: 'allfixsapp.appspot.com',
    measurementId: 'G-S877CVJ0DH',
  );
}
